backend:
  # name: git-gateway
  name: github
  repo: fraenzee/kita-grossweil
  branch: main # Die Branch, die du für dein Deployment verwendest (meist 'main' oder 'master')

media_folder: "public/bilder" # Ordner, in dem hochgeladene Bilder gespeichert werden
public_folder: "/public" # Öffentlicher Pfad zu den hochgeladenen Bildern

collections:
  - name: "pages" # Name der Sammlung (intern)
    label: "Seiten" # Anzeigename im CMS
    files:
      - label: "Startseite"
        name: "index"
        file: "src/content/pages/index.md" # Pfad zur Markdown-Datei der Startseite
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - label: "Über uns (Team)"
        name: "about"
        file: "src/content/pages/ueber-uns.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - label: "Pädagogisches Konzept"
        name: "pedagogy"
        file: "src/content/pages/paedagogik.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - label: "Anmeldung und Kosten"
        name: "registration_costs"
        file: "src/content/pages/anmeldung-kosten.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - label: "Aktuelles"
        name: "aktuelles"
        file: "src/content/pages/aktuelles.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - label: "Kontakt"
        name: "contact"
        file: "src/content/pages/kontakt.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - label: "Stellenanzeigen"
        name: "jobs"
        file: "src/content/pages/stellenanzeigen.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - label: "Datenschutz"
        name: "privacy"
        file: "src/content/pages/datenschutz.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - label: "Impressum"
        name: "imprint"
        file: "src/content/pages/impressum.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
