backend:
  name: git-gateway
    # branch: main # Die Branch, die du für dein Deployment verwendest (meist 'main' oder 'master')
      # Verwende Auth0 für die Authentifizierung
        auth_provider: netlify
          # Du musst den API-Schlüssel für die Identity-Instanz von Netlify verwenden.
            # Dies wird von der Auth0-Erweiterung konfiguriert.
              auth_token_host: https://kita-grossweil.netlify.app
                identity_url: https://kita-grossweil.netlify.app/.netlify/identity

media_folder: "public/uploads" # Ordner, in dem hochgeladene Bilder gespeichert werden
public_folder: "/uploads" # Öffentlicher Pfad zu den hochgeladenen Bildern

collections:
  - name: "pages" # Name der Sammlung (intern)
    label: "Seiten" # Anzeigename im CMS
    files:
      - label: "Startseite"
        name: "index"
        file: "src/content/pages/index.md" # Pfad zur Markdown-Datei der Startseite
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - label: "Über uns (Team)"
        name: "about"
        file: "src/content/pages/ueber-uns.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - label: "Pädagogisches Konzept"
        name: "pedagogy"
        file: "src/content/pages/paedagogik.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - label: "Anmeldung und Kosten"
        name: "registration_costs"
        file: "src/content/pages/anmeldung-kosten.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - label: "Aktuelles"
        name: "aktuelles"
        file: "src/content/pages/aktuelles.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - label: "Kontakt"
        name: "contact"
        file: "src/content/pages/kontakt.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - label: "Stellenanzeigen"
        name: "jobs"
        file: "src/content/pages/stellenanzeigen.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - label: "Datenschutz"
        name: "privacy"
        file: "src/content/pages/datenschutz.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - label: "Impressum"
        name: "imprint"
        file: "src/content/pages/impressum.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
