backend:
  # name: git-gateway
  name: github
  repo: fraenzee/kita-grossweil
  branch: main # Die Branch, die du für dein Deployment verwendest (meist 'main' oder 'master')

media_folder: "public/bilder" # Ordner, in dem hochgeladene Bilder gespeichert werden
public_folder: "/public" # Öffentlicher Pfad zu den hochgeladenen Bildern

collections:
  - name: "pages" # Name der Sammlung (intern)
    label: "Seiten" # Anzeigename im CMS
    files:
      - label: "Startseite"
        name: "index"
        file: "src/content/pages/index.md" # Pfad zur Markdown-Datei der Startseite
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - label: "Über uns"
        name: "ueber-uns"
        file: "src/content/pages/ueber-uns.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - label: "Pädagogik"
        name: "paedagogik"
        file: "src/content/pages/paedagogik.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - label: "Anmeldung & Kosten"
        name: "anmeldung-kosten"
        file: "src/content/pages/anmeldung-kosten.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - label: "Aktuelles"
        name: "aktuelles"
        file: "src/content/pages/aktuelles.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - label: "Galerie"
        name: "galerie"
        file: "src/content/pages/galerie.md"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Inhalt", name: "body", widget: "markdown" }
      - label: "Kontakt"
        name: "kontakt"
        file: "src/content/pages/kontakt.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - label: "Stellenangebote"
        name: "stellenanzeigen"
        file: "src/content/pages/stellenanzeigen.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - label: "Datenschutz"
        name: "datenschutz"
        file: "src/content/pages/datenschutz.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - label: "Impressum"
        name: "impressum"
        file: "src/content/pages/impressum.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhalt", name: "body", widget: "markdown"}
